### ISSUE TITLE
실행했을 때 발생되는 오류

### ISSUE THREAD

**Issue by taeyoung1005** [GENEXIS-AI/arXiv-PDF-Translator#1]
1. README에 나오는 라이브러리만 설치했을 때 해당 오류가 뜹니다. 아래 패키지를 추가해야 할 것 같습니다.

> FeatureNotFound( bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

`pip install lxml`

2. requirements.txt를 최신화 하는 것도 좋을 것 같습니다.

3. 번역이 아예 안됩니다 ㅠㅠ https://arxiv.org/pdf/2103.15691 이 논문으로 시도했는데 원본 PDF만 나오네요..

**Comment by GENEXIS-AI** [comment]
소중한 의견 감사합니다. 로그 정보를 같이 제공해주시면 향후 수정때 안내드리겠습니다.
아래는 제가 시도해서 번역된 결과인데, gpt-4o-mini 정확도가 낮아 2-3번 시도해야할 수도 있습니다.
[2103.15691.pdf](https://github.com/user-attachments/files/16643999/2103.15691.pdf)
